/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-11-04 04:21:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class insert_005fcustom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Main 화면</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table,th,td{border:1px solid black;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function check(){\r\n");
      out.write("\tif(document.insert.id.value==\"\"){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\tdocument.insert.id.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.insert.name.value==\"\"){\r\n");
      out.write("\t\talert(\"이름을 입력하세요.\");\r\n");
      out.write("\t\tdocument.insert.name.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.insert.passwd.value==\"\"){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\tdocument.insert.passwd.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.insert.passwd2.value==\"\"){\r\n");
      out.write("\t\talert(\"확인 비밀번호를 입력하세요.\");\r\n");
      out.write("\t\tdocument.insert.passwd2.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.insert.passwd.value!=document.insert.passwd2.value){\r\n");
      out.write("\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\tdocument.insert.passwd2.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.insert.submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	Connection conn = null;
	PreparedStatement pstmt = null;
	ResultSet rs = null;

	String user = "yangjung";
	String password = "1234";
	String url ="jdbc:oracle:thin:@127.0.0.1:1521:orcl";
	
	Class.forName("oracle.jdbc.driver.OracleDriver");
	conn = DriverManager.getConnection(url, user, password);
	request.setCharacterEncoding("utf-8");
	int a = 0;
	try{
		String sql = "SELECT last_number FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER('hrd0916')";
		pstmt = conn.prepareStatement(sql);
		rs = pstmt.executeQuery();
		while(rs.next()){
			a = rs.getInt(1)+1;
			
		}
				
	}catch (SQLException e){
		out.println("테이블 호출 실패"+e.getMessage());
	}finally{
		if(rs!=null) rs.close();
		if(pstmt!=null) pstmt.close();
		if(conn!=null) conn.close();
	}

      out.write("\r\n");
      out.write("<table width=100% height=100%>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td valign=\"top\" height='80%' bgcolor=\"gray\">\r\n");
      out.write("<form name=\"insert\" method=\"post\" action=\"custom_insert.jsp\" >\r\n");
      out.write("<span style=\"font-weight:bold;font-size:20px;\">고객 정보 등록화면</span>\r\n");
      out.write("<table align=\"center\" width=80%>\r\n");
      out.write("<tr>\r\n");
      out.write("<th width=\"120\">아이디</th><td><input type=\"text\" size=\"30\" name=\"id\" value=\"");
      out.print(a );
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>이름</th><td><input type=\"text\" size=\"30\" name=\"name\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>비밀번호</th><td><input type=\"password\" size=\"30\" name=\"passwd\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>비밀번호확인</th><td><input type=\"password\" size=\"30\" name=\"passwd2\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>성별</th><td>\r\n");
      out.write("<input type=\"radio\" size=\"30\" name=\"gender\" value=\"1\">남\r\n");
      out.write("<input type=\"radio\" size=\"30\" name=\"gender\" value=\"2\">여</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>이름</th><td><input type=\"text\" size=\"30\" name=\"email1\">@\r\n");
      out.write("<select name=\"email2\">\r\n");
      out.write("\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t<option value=\"korea.com\">korea.com</option>\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>핸드폰</th><td>\r\n");
      out.write("<select name=\"ph1\" style=\"width:82;\">\r\n");
      out.write("\t<option value=\"010\">010</option>\r\n");
      out.write("\t<option value=\"011\">011</option>\r\n");
      out.write("\t<option value=\"019\">019</option>\r\n");
      out.write("</select>\r\n");
      out.write(" - <input type=\"text\" size=\"7\" name=\"ph2\"> - <input type=\"text\" size=\"7\" name=\"ph3\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>전화번호</th><td>\r\n");
      out.write("<input type=\"text\" size=\"7\" name=\"tel1\"> - \r\n");
      out.write("<input type=\"text\" size=\"7\" name=\"tel2\"> - \r\n");
      out.write("<input type=\"text\" size=\"7\" name=\"tel3\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>주소</th><td><input type=\"text\" size=\"60\" name=\"adress\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>차량번호</th><td><input type=\"text\" size=\"30\" name=\"carnumber\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>차량종류</th><td><input type=\"text\" size=\"30\" name=\"cartype\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th colspan=\"2\">\r\n");
      out.write("<button type=\"button\" onclick=\"javascript:check()\">고객등록</button> <button type=\"reset\">다시작성</button>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
